language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  - TEST_COMMAND="istanbul cover ./test/test.js"
  - TEST_COMMAND="phantomjs ./test/test.js ../dist/lodash.compat.js"
  - TEST_COMMAND="phantomjs ./test/test.js ../dist/lodash.compat.min.js"
  - TEST_COMMAND="node ./test/test.js ../dist/lodash.js"
  - TEST_COMMAND="node ./test/test.js ../dist/lodash.min.js"
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "npm install -g istanbul"
script:
  - $TEST_COMMAND
